import Sidebar from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overflow-hidden ${inter.className}`}>
        <main className="flex flex-1 h-screen w-full p-0 overflow-hidden">
          <Sidebar />
          <div className="border-l-[1px] border-l-pink-200 w-full min-h-screen overflow-y-auto bg-gradient-to-tr from-purple-200 to-purple-100 dark:from-zinc-900 dark:to-zinc-800">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
